services:
  api:
    build:
      context: .
      dockerfile: ./dockerfile
      args:
        # These would come from GitHub variables in CI/CD
        API_HOST: ${API_HOST}
        API_PORT: ${API_PORT}
        LOG_LEVEL: ${LOG_LEVEL}
        # These would come from GitHub secrets in CI/CD
        PGSQL_HOST: ${DB_HOST}
        PGSQL_PORT: ${DB_PORT}
        PGSQL_USER: ${DB_USER}
        PGSQL_PASSWORD: ${DB_PASSWORD}
        PGSQL_NAME: ${DB_NAME}       
    image: rear-diff-image
    container_name: rear-diff-container
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    networks:
      - rear-diff-network

networks:
  rear-diff-network:
    driver: bridge